### ISSUE TITLE
Problem with Chrome extension "Google Analytics Opt-out Add-on (by Google)"

### ISSUE THREAD

**Issue by vbauer** [revolunet/angular-google-analytics#16]
Hello, Julien!

We faced in our project with some strange problem:
When users begin to use plugin "Google Analytics Opt-out Add-on (by Google)" (https://chrome.google.com/webstore/detail/google-analytics-opt-out/fllaojicojecljbmefodhfapmkghcbnh) in Google Chrome, our application breaks.

```
TypeError: Cannot read property 'length' of undefined
    at $interpolate (http://localhost:8080/static/lib.js:27215:24)
    at ngBindTemplateDirective (http://localhost:8080/static/lib.js:36314:25)
    at nodeLinkFn (http://localhost:8080/static/lib.js:25212:13)
    at compositeLinkFn (http://localhost:8080/static/lib.js:24623:15)
    at compositeLinkFn (http://localhost:8080/static/lib.js:24626:13)
    at nodeLinkFn (http://localhost:8080/static/lib.js:25206:24)
    at compositeLinkFn (http://localhost:8080/static/lib.js:24623:15)
    at publicLinkFn (http://localhost:8080/static/lib.js:24528:30)
    at http://localhost:8080/static/lib.js:20247:27
    at Scope.$get.Scope.$eval (http://localhost:8080/static/lib.js:30986:28)  lib.js:28444
TypeError: Cannot read property 'childNodes' of undefined
    at compositeLinkFn (http://localhost:8080/static/lib.js:24626:36)
    at compositeLinkFn (http://localhost:8080/static/lib.js:24626:13)
    at nodeLinkFn (http://localhost:8080/static/lib.js:25206:24)
    at compositeLinkFn (http://localhost:8080/static/lib.js:24623:15)
    at publicLinkFn (http://localhost:8080/static/lib.js:24528:30)
    at http://localhost:8080/static/lib.js:20247:27
    at Scope.$get.Scope.$eval (http://localhost:8080/static/lib.js:30986:28)
    at Scope.$get.Scope.$apply (http://localhost:8080/static/lib.js:31086:23)
    at http://localhost:8080/static/lib.js:20245:15
    at Object.invoke (http://localhost:8080/static/lib.js:22661:17) undefined lib.js:28444
...
```

(lib.js is a concatenated version of all JS libraries)

Another strange moment, that in output HTML file "script" tags with GA are before "head" tag:
![Image](https://f.cloud.github.com/assets/578021/2237857/9acb2032-9bcb-11e3-9137-4fee3d4a3571.png)

When we turn off this plugin everything well.

Could you please help us with it? Any idea will be great!

**Comment by bluecollarcoder** [comment]
I ran into a similar problem with my Angular app blowing up with Chrome extensions. The problem that I saw was that the extension was inserting custom scripts onto the page and moving my existing script tags from `<head>` into `<html>`. When I moved my root controller from `<html ng-app="app" ng-controller="AppCtrl">` to `<body ng-app="app", ng-controller="AppCtrl">`, everything worked.
